# Implementation of eRPC for GRBLHAL IOStreams.

#
# Generated by erpcgen 1.9.0 on Sun Jun  5 12:51:54 2022.
#
# AUTOGENERATED - DO NOT EDIT
#


# Structures data types declarations
class rpc_coolant_state_t(object):
    def __init__(self, flood=None, mist=None, shower=None, through_spindle=None):
        self.flood = flood # uint8
        self.mist = mist # uint8
        self.shower = shower # uint8
        self.through_spindle = through_spindle # uint8

    def _read(self, codec):
        self.flood = codec.read_uint8()
        self.mist = codec.read_uint8()
        self.shower = codec.read_uint8()
        self.through_spindle = codec.read_uint8()
        return self

    def _write(self, codec):
        if self.flood is None:
            raise ValueError("flood is None")
        codec.write_uint8(self.flood)
        if self.mist is None:
            raise ValueError("mist is None")
        codec.write_uint8(self.mist)
        if self.shower is None:
            raise ValueError("shower is None")
        codec.write_uint8(self.shower)
        if self.through_spindle is None:
            raise ValueError("through_spindle is None")
        codec.write_uint8(self.through_spindle)

    def __str__(self):
        return "<%s@%x flood=%s mist=%s shower=%s through_spindle=%s>" % (self.__class__.__name__, id(self), self.flood, self.mist, self.shower, self.through_spindle)

    def __repr__(self):
        return self.__str__()

