# Implementation of eRPC for GRBLHAL IOStreams.

#
# Generated by erpcgen 1.9.0 on Sat Jun  4 22:11:33 2022.
#
# AUTOGENERATED - DO NOT EDIT
#


# Structures data types declarations
class rpc_coolant_state(object):
    def __init__(self, flood=None, mist=None, shower=None, through_spindle=None):
        self.flood = flood # bool
        self.mist = mist # bool
        self.shower = shower # bool
        self.through_spindle = through_spindle # bool

    def _read(self, codec):
        self.flood = codec.read_bool()
        self.mist = codec.read_bool()
        self.shower = codec.read_bool()
        self.through_spindle = codec.read_bool()
        return self

    def _write(self, codec):
        if self.flood is None:
            raise ValueError("flood is None")
        codec.write_bool(self.flood)
        if self.mist is None:
            raise ValueError("mist is None")
        codec.write_bool(self.mist)
        if self.shower is None:
            raise ValueError("shower is None")
        codec.write_bool(self.shower)
        if self.through_spindle is None:
            raise ValueError("through_spindle is None")
        codec.write_bool(self.through_spindle)

    def __str__(self):
        return "<%s@%x flood=%s mist=%s shower=%s through_spindle=%s>" % (self.__class__.__name__, id(self), self.flood, self.mist, self.shower, self.through_spindle)

    def __repr__(self):
        return self.__str__()

