# Implementation of eRPC for GRBLHAL IOStreams.

#
# Generated by erpcgen 1.9.0 on Sat Jun  4 22:11:33 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for GRBLHALService
class IGRBLHALService(object):
    SERVICE_ID = 1
    LED_ON_ID = 1
    LED_OFF_ID = 2
    GET_COOLANT_STATE_ID = 3

    def led_on(self, led):
        raise NotImplementedError()

    def led_off(self, led):
        raise NotImplementedError()

    def get_coolant_state(self):
        raise NotImplementedError()


