# Implementation of eRPC for GRBLHAL IOStreams.

#
# Generated by erpcgen 1.9.0 on Sun Jun  5 12:51:54 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

# Abstract base class for GRBLHALService
class IGRBLHALService(object):
    SERVICE_ID = 1
    LED_ON_ID = 1
    LED_OFF_ID = 2
    RPC_GET_COOLANT_STATE_ID = 3
    RPC_GET_INTEGER_ID = 4

    def led_on(self, led):
        raise NotImplementedError()

    def led_off(self, led):
        raise NotImplementedError()

    def rpc_get_coolant_state(self):
        raise NotImplementedError()

    def rpc_get_integer(self):
        raise NotImplementedError()


