# Implementation of eRPC for GRBLHAL IOStreams.

#
# Generated by erpcgen 1.9.0 on Sat Jun  4 22:11:33 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for GRBLHALService
class GRBLHALServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(GRBLHALServiceService, self).__init__(interface.IGRBLHALService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IGRBLHALService.LED_ON_ID: self._handle_led_on,
                interface.IGRBLHALService.LED_OFF_ID: self._handle_led_off,
                interface.IGRBLHALService.GET_COOLANT_STATE_ID: self._handle_get_coolant_state,
            }

    def _handle_led_on(self, sequence, codec):
        # Read incoming parameters.
        led = codec.read_uint8()

        # Invoke user implementation of remote function.
        self._handler.led_on(led)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.LED_ON_ID,
            sequence=sequence))

    def _handle_led_off(self, sequence, codec):
        # Read incoming parameters.
        led = codec.read_uint8()

        # Invoke user implementation of remote function.
        self._handler.led_off(led)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.LED_OFF_ID,
            sequence=sequence))

    def _handle_get_coolant_state(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.get_coolant_state()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.GET_COOLANT_STATE_ID,
            sequence=sequence))
        _result._write(codec)


