# Implementation of eRPC for GRBLHAL IOStreams.

#
# Generated by erpcgen 1.9.0 on Sun Jun  5 12:51:54 2022.
#
# AUTOGENERATED - DO NOT EDIT
#

import erpc
from . import common, interface

# Client for GRBLHALService
class GRBLHALServiceService(erpc.server.Service):
    def __init__(self, handler):
        super(GRBLHALServiceService, self).__init__(interface.IGRBLHALService.SERVICE_ID)
        self._handler = handler
        self._methods = {
                interface.IGRBLHALService.LED_ON_ID: self._handle_led_on,
                interface.IGRBLHALService.LED_OFF_ID: self._handle_led_off,
                interface.IGRBLHALService.RPC_GET_COOLANT_STATE_ID: self._handle_rpc_get_coolant_state,
                interface.IGRBLHALService.RPC_GET_INTEGER_ID: self._handle_rpc_get_integer,
            }

    def _handle_led_on(self, sequence, codec):
        # Read incoming parameters.
        led = codec.read_uint8()

        # Invoke user implementation of remote function.
        self._handler.led_on(led)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.LED_ON_ID,
            sequence=sequence))

    def _handle_led_off(self, sequence, codec):
        # Read incoming parameters.
        led = codec.read_uint8()

        # Invoke user implementation of remote function.
        self._handler.led_off(led)

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.LED_OFF_ID,
            sequence=sequence))

    def _handle_rpc_get_coolant_state(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.rpc_get_coolant_state()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.RPC_GET_COOLANT_STATE_ID,
            sequence=sequence))
        _result._write(codec)

    def _handle_rpc_get_integer(self, sequence, codec):
        # Read incoming parameters.

        # Invoke user implementation of remote function.
        _result = self._handler.rpc_get_integer()

        # Prepare codec for reply message.
        codec.reset()

        # Construct reply message.
        codec.start_write_message(erpc.codec.MessageInfo(
            type=erpc.codec.MessageType.kReplyMessage,
            service=interface.IGRBLHALService.SERVICE_ID,
            request=interface.IGRBLHALService.RPC_GET_INTEGER_ID,
            sequence=sequence))
        codec.write_uint8(_result)


