/*
 * Implementation of eRPC for GRBLHAL IOStreams.
 */

/*
 * Generated by erpcgen 1.9.0 on Sat Jun  4 17:37:32 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_grblhal_rpc_h_)
#define _grblhal_rpc_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

#endif // ERPC_TYPE_DEFINITIONS

/*! @brief GRBLHALService identifiers */
enum _GRBLHALService_ids
{
    kGRBLHALService_service_id = 1,
    kGRBLHALService_led_on_id = 1,
    kGRBLHALService_led_off_id = 2,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name GRBLHALService
//@{
void led_on(uint8_t led);

void led_off(uint8_t led);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _grblhal_rpc_h_
