/*
 * Implementation of eRPC for GRBLHAL IOStreams.
 */

/*
 * Generated by erpcgen 1.9.0 on Sat Jun  4 22:10:58 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_grblhal_rpc_h_)
#define _grblhal_rpc_h_

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include "erpc_version.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

#if !defined(ERPC_TYPE_DEFINITIONS)
#define ERPC_TYPE_DEFINITIONS

// Aliases data types declarations
typedef struct rpc_coolant_state rpc_coolant_state;

// Structures/unions data types declarations
struct rpc_coolant_state
{
    bool flood;
    bool mist;
    bool shower;
    bool through_spindle;
};


#endif // ERPC_TYPE_DEFINITIONS

/*! @brief GRBLHALService identifiers */
enum _GRBLHALService_ids
{
    kGRBLHALService_service_id = 1,
    kGRBLHALService_led_on_id = 1,
    kGRBLHALService_led_off_id = 2,
    kGRBLHALService_get_coolant_state_id = 3,
};

#if defined(__cplusplus)
extern "C" {
#endif

//! @name GRBLHALService
//@{
void led_on(uint8_t led);

void led_off(uint8_t led);

rpc_coolant_state * get_coolant_state(void);
//@}

#if defined(__cplusplus)
}
#endif

#endif // _grblhal_rpc_h_
