/*
 * Implementation of eRPC for GRBLHAL IOStreams.
 */

/*
 * Generated by erpcgen 1.9.0 on Sat Jun  4 22:10:58 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#if !defined(_grblhal_rpc_server_h_)
#define _grblhal_rpc_server_h_

#ifdef __cplusplus
#include "erpc_server.h"
#include "erpc_codec.h"
extern "C"
{
#include "grblhal_rpc.h"
#include <stdint.h>
#include <stdbool.h>
}

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif


/*!
 * @brief Service subclass for GRBLHALService.
 */
class GRBLHALService_service : public erpc::Service
{
public:
    GRBLHALService_service() : Service(kGRBLHALService_service_id) {}

    /*! @brief Call the correct server shim based on method unique ID. */
    virtual erpc_status_t handleInvocation(uint32_t methodId, uint32_t sequence, erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory);

private:
    /*! @brief Server shim for led_on of GRBLHALService interface. */
    erpc_status_t led_on_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for led_off of GRBLHALService interface. */
    erpc_status_t led_off_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);

    /*! @brief Server shim for get_coolant_state of GRBLHALService interface. */
    erpc_status_t get_coolant_state_shim(erpc::Codec * codec, erpc::MessageBufferFactory *messageFactory, uint32_t sequence);
};

extern "C" {
#else
#include "grblhal_rpc.h"
#endif // __cplusplus

typedef void * erpc_service_t;

erpc_service_t create_GRBLHALService_service(void);

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
void destroy_GRBLHALService_service(erpc_service_t service);
#elif ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_STATIC
void destroy_GRBLHALService_service(void);
#else
#warning "Unknown eRPC allocation policy!"
#endif

#ifdef __cplusplus
}
#endif // __cplusplus

#endif // _grblhal_rpc_server_h_
