/*
 * Implementation of eRPC for GRBLHAL IOStreams.
 */

/*
 * Generated by erpcgen 1.9.0 on Sat Jun  4 17:37:32 2022.
 *
 * AUTOGENERATED - DO NOT EDIT
 */


#include "grblhal_rpc_server.h"
#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
#include <new>
#include "erpc_port.h"
#endif
#include "erpc_manually_constructed.h"

#if 10900 != ERPC_VERSION_NUMBER
#error "The generated shim code version is different to the rest of eRPC code."
#endif

using namespace erpc;
using namespace std;

#if ERPC_NESTED_CALLS_DETECTION
extern bool nestingDetection;
#endif

ERPC_MANUALLY_CONSTRUCTED_STATIC(GRBLHALService_service, s_GRBLHALService_service);



// Call the correct server shim based on method unique ID.
erpc_status_t GRBLHALService_service::handleInvocation(uint32_t methodId, uint32_t sequence, Codec * codec, MessageBufferFactory *messageFactory)
{
    erpc_status_t erpcStatus;
    switch (methodId)
    {
        case kGRBLHALService_led_on_id:
        {
            erpcStatus = led_on_shim(codec, messageFactory, sequence);
            break;
        }

        case kGRBLHALService_led_off_id:
        {
            erpcStatus = led_off_shim(codec, messageFactory, sequence);
            break;
        }

        default:
        {
            erpcStatus = kErpcStatus_InvalidArgument;
            break;
        }
    }

    return erpcStatus;
}

// Server shim for led_on of GRBLHALService interface.
erpc_status_t GRBLHALService_service::led_on_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t led;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(&led);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        led_on(led);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kGRBLHALService_service_id, kGRBLHALService_led_on_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

// Server shim for led_off of GRBLHALService interface.
erpc_status_t GRBLHALService_service::led_off_shim(Codec * codec, MessageBufferFactory *messageFactory, uint32_t sequence)
{
    erpc_status_t err = kErpcStatus_Success;

    uint8_t led;

    // startReadMessage() was already called before this shim was invoked.

    codec->read(&led);

    err = codec->getStatus();
    if (err == kErpcStatus_Success)
    {
        // Invoke the actual served function.
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = true;
#endif
        led_off(led);
#if ERPC_NESTED_CALLS_DETECTION
        nestingDetection = false;
#endif

        // preparing MessageBuffer for serializing data
        err = messageFactory->prepareServerBufferForSend(codec->getBuffer());
    }

    if (err == kErpcStatus_Success)
    {
        // preparing codec for serializing data
        codec->reset();

        // Build response message.
        codec->startWriteMessage(kReplyMessage, kGRBLHALService_service_id, kGRBLHALService_led_off_id, sequence);

        err = codec->getStatus();
    }

    return err;
}

#if ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_DYNAMIC
erpc_service_t create_GRBLHALService_service()
{
    return new (nothrow) GRBLHALService_service();
}

void destroy_GRBLHALService_service(erpc_service_t service)
{
    if (service)
    {
        delete (GRBLHALService_service *)service;
    }
}
#elif ERPC_ALLOCATION_POLICY == ERPC_ALLOCATION_POLICY_STATIC
erpc_service_t create_GRBLHALService_service()
{
    s_GRBLHALService_service.construct();
    return s_GRBLHALService_service.get();
}

void destroy_GRBLHALService_service()
{
    s_GRBLHALService_service.destroy();
}
#else
#warning "Unknown eRPC allocation policy!"
#endif
